### ISSUE TITLE
另外部署了一个文档站点，译者们介意的话我去关了

### ISSUE THREAD

**Issue by witjs** [Nugine/deno-manual-cn#14]
把这个文档部署到了http://deno.me 这个域名下
没有做任何更改
保留了所有的信息
只是为了方便记忆
所有的翻译贡献者们介意吗
介意的话我关掉

**Comment by Nugine** [comment]
Deno 使用 MIT 协议 <https://github.com/denoland/deno/blob/master/LICENSE>

本项目是基于 Deno 源文件的再创作，使用 CC BY-NC 4.0 协议 <https://github.com/Nugine/deno-manual-cn/blob/master/LICENSE>

协议概要 <https://creativecommons.org/licenses/by-nc/4.0/deed.zh>

本仓库引用 Deno 仓库作为子模块，文档首页提供了指向 Deno 仓库和本仓库的链接。

通过遵守本项目的协议，您可以获得以下权利：

+ 共享 — 在任何媒介以任何形式复制、发行本作品
+ 演绎 — 修改、转换或以本作品为基础进行创作 

您必须遵守以下条件：

+ 署名 — 您必须给出适当的署名，提供指向本许可协议的链接，同时标明是否对原始作品作了修改。您可以用任何合理的方式来署名，但是不得以任何方式暗示许可人为您或您的使用背书。
+ 非商业性使用 — 您不得将本作品用于商业目的。 

不作任何修改的镜像部署可视为遵守了署名条件，因为本文档已经提供了自我链接。第二条件是禁止商业使用，您不得利用本作品获取商业利益。如果我们发现违反条件的行为，您将失去以上权利。

综上，不作任何修改的非商业性镜像部署符合本项目的协议，允许使用。希望您认同知识共享精神，欢迎参与本项目的宣传与改进工作。
